---
# Title: role-gog
#
# Author: bitfinity.nl
# File: tasks/gogs.yml
#
# Description:
#   A painless self-hosted Git service.
#
# Sources:
#   https://gogs.io/

- name: "Install packages"
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes 
  vars:
    packages:
    - git
    - wget

- name: "Create a gogs group"
  group:
    name: gogs

- name: "Create a gogs system user"
  user:
    name: gogs
    group: gogs
    state: present

- name: "Download binary Gogs from Github"
  get_url:
    url: "{{ gogs_version }}"
    dest: /tmp/

- name: "Unpack binary"
  unarchive:
    src: /tmp/linux_amd64.tar.gz
    dest: /opt/
    owner: gogs
    group: gogs
    mode: 0755
    remote_src: yes

- name: "copy gogs systemd service file to /etc/systemd/system/"
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: gogs
    group: gogs
    mode: "{{ item.mode }}"
  with_items:
    - { src: 'gogs/app.ini.j2', dest: '/opt/gogs/custom/conf/app.ini', mode: '0644', desc: 'Gogs Configuration' }
    - { src: 'gogs/gogs.service.j2', dest: '/etc/systemd/system/gogs.service', mode: '0777', desc: 'For systemd service' }

#- name: "Create gogs admin user"
#  command: ./gogs admin create-user --name "{{ gogs_admin_user }}" --password "{{ gogs_admin_pass }}" --admin --email "{{ gogs_admin_mail }}"
#  become: yes
#  become_user: ansible
#  args:
#    chdir: /opt/gogs

- name: "Start and enable services"
  systemd:
    name: gogs
    state: started
    enabled: yes
    